class project {
  static String dev_aws_account     = "665900821133"
  static String prod_aws_account    = ""
  static String dev_cluster         = "jbroussard-demo"
  static String qa_cluster          = ""
  static String stage_cluster       = ""
  static String prod_cluster        = ""
  static String stageuswest_cluster = ""
  static String old_prod_cluster    = ""
  static String dev_profile         = "jbroussard-demo"
  static String prod_profile        = ""
  static String old_prod_profile    = ""
  static String dev_region          = "us-east-1"
  static String prod_region         = ""
  static String produswest_region   = ""
  static String produseast_region   = ""
  static String build_notify        = "jamie@jamiebroussard.com"
  static String region              = "us-east-1"
}
