class project {
  static String dev_aws_account     = "087395885892"
  static String prod_aws_account    = "646754184262"
  static String dev_cluster         = "xcijv-dev-eks-cluster-alpha"
  static String qa_cluster          = "xcijv-qa"
  static String stage_cluster       = "useast-stage-eks-cluster"
  static String prod_cluster        = "useast-prod-eks-cluster"
  static String stageuswest_cluster = "uswest-stage-eks-cluster"
  static String old_prod_cluster    = "xcijv-prod-eks-cluster"
  static String dev_profile         = "xcijv_us_dev_qa"
  static String prod_profile        = "xcijv_us_stage_prod_east"
  static String old_prod_profile    = "xcijv_us_dev_qa"
  static String dev_region          = "us-east-1"
  static String prod_region         = "us-east-1"
  static String produswest_region   = "us-west-2"
  static String produseast_region   = "us-east-1"
  static String build_notify        = "xcijv-pkdev@prokarma.com"
  static String region              = "us-east-1"
}
